### PR TITLE
fix#21, race condition when use encoder/decoder

### PR DESCRIPTION
**Pull request by orientlu**

### CODE REVIEW

**Comment by 256dpi** [comment]
Thanks for the contribution! However, the encoders and decoders are not meant for concurrent use. All dependent code in gomqtt uses some sort of locking or synchronization to ensure there is only one reader and writer. The encoder could potentially be used by multiple goroutines, if the underlying transport provides atomic-like writes. But the accessing the decoder concurrently will almost certainly lead to issues if multiple goroutines are reading from the underlying transport. Thus, I'm opting to leave the API as is with potentially adding a comment on the thread-unsafety.

**Comment by orientlu** [comment]
Thanks for your reply! I use this package to build my own MQTT broker, Encoder.Write()  support concurrent use can inprove transmission efficiency
```
package1: encode -> write buffer
package2: ---------- encode ->   write buffer     (concurrency)
comparison
package1: encode-> write buffer 
package2: ----------------------- encode -> wriete buffer
```

**Comment by 256dpi** [comment]
Ok, I can see some usefulness here. Using a pool to cache the buffers sounds generally like a good step forward also in terms of memory efficiency. A broker with many connections would presumably use a lot less memory if the buffers are pooled among all connections. Could you update the PR so that there is only one global pool?

**Comment by orientlu** [comment]
up~

**Comment by 256dpi** [comment]
Thanks!

**Pull request merged**
